# This workflow will build a Java project with Maven
# For more information see: https://help.github.com/actions/language-and-framework-guides/building-and-testing-java-with-maven

name: Java CI with Maven

on:
  push:
    branches: 'master'
  pull_request:
    branches: 'master'

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout CustomWhiteList
      uses: actions/checkout@v1
    - name: Set up JDK 8
      uses: actions/setup-java@v1
      with:
        java-version: 1.8
    
# Setup and run BuildTools
    - name: Setup BuildTools
      run: mkdir BuildTools && wget -O BuildTools/BuildTools.jar https://hub.spigotmc.org/jenkins/job/BuildTools/lastSuccessfulBuild/artifact/target/BuildTools.jar
    - name: Check 1.12.2
      id: color
      run: test -f ~/.m2/repository/org/bukkit/craftbukkit/1.12.2-R0.1-SNAPSHOT/craftbukkit-1.12.2-R0.1-SNAPSHOT.jar && echo "::set-output name=sucess::true" || echo "::set-output name=sucess::false"
    - name: Build 1.12.2
      if: steps.color.outputs.sucess != 'true'
      run: cd BuildTools && java -jar BuildTools.jar --rev 1.12.2
    
#build the package  
    - name: Build with Maven
      run: mvn -B package --file pom.xml

    - name: Stage jar
      run: mkdir staging && cp CustonWhiteList/CustomWhiteList/target/CustomWhiteList*.jar staging
    - name: Rename jar
      run: mv staging/CustomWhiteList*.jar staging/CustomWhiteList_$GITHUB_SHA.jar
    - name: Upload jar
      uses: actions/upload-artifact@v2
      with:
        name: CustomWhiteList_Dev-Build
        path: staging/CustomWhiteList_*.jar
